// Profession salary data based on BLS (Bureau of Labor Statistics) data
// Data represents 2025 estimates for common professions

export interface ProfessionData {
  slug: string;
  title: string;
  category: string;
  medianSalary: number;
  percentile25: number;
  percentile50: number;
  percentile75: number;
  percentile90: number;
  hourlyMedian: number;
  description: string;
  education: string;
  outlook: string;
  skills: string[];
}

export const professions: ProfessionData[] = [
  // Technology & Engineering
  {
    slug: 'software-engineer',
    title: 'Software Engineer',
    category: 'Technology',
    medianSalary: 120000,
    percentile25: 85000,
    percentile50: 120000,
    percentile75: 160000,
    percentile90: 200000,
    hourlyMedian: 57.69,
    description: 'Design, develop, and maintain software applications and systems.',
    education: "Bachelor's degree in Computer Science or related field",
    outlook: 'Much faster than average (22% growth)',
    skills: ['Programming', 'Problem Solving', 'Algorithms', 'System Design'],
  },
  {
    slug: 'data-scientist',
    title: 'Data Scientist',
    category: 'Technology',
    medianSalary: 130000,
    percentile25: 95000,
    percentile50: 130000,
    percentile75: 170000,
    percentile90: 210000,
    hourlyMedian: 62.50,
    description: 'Analyze complex data to help organizations make better decisions.',
    education: "Master's degree in Data Science, Statistics, or related field",
    outlook: 'Much faster than average (36% growth)',
    skills: ['Python', 'Machine Learning', 'Statistics', 'Data Visualization'],
  },
  {
    slug: 'web-developer',
    title: 'Web Developer',
    category: 'Technology',
    medianSalary: 85000,
    percentile25: 60000,
    percentile50: 85000,
    percentile75: 115000,
    percentile90: 145000,
    hourlyMedian: 40.87,
    description: 'Build and maintain websites and web applications.',
    education: "Associate's degree or bootcamp certification",
    outlook: 'Faster than average (13% growth)',
    skills: ['HTML/CSS', 'JavaScript', 'React', 'Node.js'],
  },
  {
    slug: 'devops-engineer',
    title: 'DevOps Engineer',
    category: 'Technology',
    medianSalary: 125000,
    percentile25: 90000,
    percentile50: 125000,
    percentile75: 165000,
    percentile90: 200000,
    hourlyMedian: 60.10,
    description: 'Manage infrastructure, automate deployments, and ensure system reliability.',
    education: "Bachelor's degree in Computer Science or related field",
    outlook: 'Much faster than average (25% growth)',
    skills: ['AWS/Azure', 'Docker', 'Kubernetes', 'CI/CD'],
  },
  {
    slug: 'product-manager',
    title: 'Product Manager',
    category: 'Technology',
    medianSalary: 135000,
    percentile25: 100000,
    percentile50: 135000,
    percentile75: 175000,
    percentile90: 220000,
    hourlyMedian: 64.90,
    description: 'Define product strategy and roadmap, working with engineering and design teams.',
    education: "Bachelor's degree in Business, Computer Science, or related field",
    outlook: 'Faster than average (14% growth)',
    skills: ['Product Strategy', 'Agile', 'User Research', 'Analytics'],
  },
  {
    slug: 'ux-designer',
    title: 'UX Designer',
    category: 'Technology',
    medianSalary: 95000,
    percentile25: 70000,
    percentile50: 95000,
    percentile75: 125000,
    percentile90: 155000,
    hourlyMedian: 45.67,
    description: 'Design user interfaces and experiences for digital products.',
    education: "Bachelor's degree in Design, HCI, or related field",
    outlook: 'Faster than average (16% growth)',
    skills: ['Figma', 'User Research', 'Prototyping', 'Interaction Design'],
  },
  {
    slug: 'cybersecurity-analyst',
    title: 'Cybersecurity Analyst',
    category: 'Technology',
    medianSalary: 110000,
    percentile25: 80000,
    percentile50: 110000,
    percentile75: 145000,
    percentile90: 180000,
    hourlyMedian: 52.88,
    description: 'Protect computer systems and networks from security threats.',
    education: "Bachelor's degree in Cybersecurity or related field",
    outlook: 'Much faster than average (32% growth)',
    skills: ['Network Security', 'Penetration Testing', 'SIEM', 'Compliance'],
  },
  {
    slug: 'cloud-architect',
    title: 'Cloud Architect',
    category: 'Technology',
    medianSalary: 145000,
    percentile25: 110000,
    percentile50: 145000,
    percentile75: 185000,
    percentile90: 230000,
    hourlyMedian: 69.71,
    description: 'Design and implement cloud computing strategies and infrastructure.',
    education: "Bachelor's degree in Computer Science plus cloud certifications",
    outlook: 'Much faster than average (28% growth)',
    skills: ['AWS/Azure/GCP', 'Architecture', 'Security', 'Cost Optimization'],
  },
  {
    slug: 'machine-learning-engineer',
    title: 'Machine Learning Engineer',
    category: 'Technology',
    medianSalary: 140000,
    percentile25: 105000,
    percentile50: 140000,
    percentile75: 180000,
    percentile90: 225000,
    hourlyMedian: 67.31,
    description: 'Build and deploy machine learning models and AI systems.',
    education: "Master's degree in Computer Science or related field",
    outlook: 'Much faster than average (40% growth)',
    skills: ['Python', 'TensorFlow', 'PyTorch', 'Deep Learning'],
  },
  {
    slug: 'database-administrator',
    title: 'Database Administrator',
    category: 'Technology',
    medianSalary: 100000,
    percentile25: 75000,
    percentile50: 100000,
    percentile75: 130000,
    percentile90: 160000,
    hourlyMedian: 48.08,
    description: 'Manage and maintain database systems and ensure data integrity.',
    education: "Bachelor's degree in Computer Science or related field",
    outlook: 'Average growth (8% growth)',
    skills: ['SQL', 'Database Design', 'Performance Tuning', 'Backup/Recovery'],
  },

  // Healthcare
  {
    slug: 'registered-nurse',
    title: 'Registered Nurse',
    category: 'Healthcare',
    medianSalary: 82000,
    percentile25: 65000,
    percentile50: 82000,
    percentile75: 100000,
    percentile90: 120000,
    hourlyMedian: 39.42,
    description: 'Provide patient care, educate patients, and coordinate with healthcare teams.',
    education: "Bachelor's of Science in Nursing (BSN) and RN license",
    outlook: 'Faster than average (6% growth)',
    skills: ['Patient Care', 'Medical Knowledge', 'Communication', 'Critical Thinking'],
  },
  {
    slug: 'physician',
    title: 'Physician',
    category: 'Healthcare',
    medianSalary: 220000,
    percentile25: 180000,
    percentile50: 220000,
    percentile75: 280000,
    percentile90: 350000,
    hourlyMedian: 105.77,
    description: 'Diagnose and treat illnesses, injuries, and medical conditions.',
    education: 'Medical degree (MD or DO) plus residency',
    outlook: 'Faster than average (3% growth)',
    skills: ['Medical Diagnosis', 'Patient Care', 'Clinical Skills', 'Communication'],
  },
  {
    slug: 'pharmacist',
    title: 'Pharmacist',
    category: 'Healthcare',
    medianSalary: 135000,
    percentile25: 115000,
    percentile50: 135000,
    percentile75: 155000,
    percentile90: 170000,
    hourlyMedian: 64.90,
    description: 'Dispense medications and provide pharmaceutical care to patients.',
    education: 'Doctor of Pharmacy (PharmD) degree',
    outlook: 'Slower than average (2% growth)',
    skills: ['Pharmacology', 'Patient Counseling', 'Drug Interactions', 'Regulations'],
  },
  {
    slug: 'physical-therapist',
    title: 'Physical Therapist',
    category: 'Healthcare',
    medianSalary: 95000,
    percentile25: 75000,
    percentile50: 95000,
    percentile75: 115000,
    percentile90: 135000,
    hourlyMedian: 45.67,
    description: 'Help patients recover from injuries and improve mobility.',
    education: 'Doctor of Physical Therapy (DPT) degree',
    outlook: 'Much faster than average (15% growth)',
    skills: ['Rehabilitation', 'Exercise Therapy', 'Patient Assessment', 'Manual Therapy'],
  },
  {
    slug: 'dental-hygienist',
    title: 'Dental Hygienist',
    category: 'Healthcare',
    medianSalary: 82000,
    percentile25: 65000,
    percentile50: 82000,
    percentile75: 95000,
    percentile90: 110000,
    hourlyMedian: 39.42,
    description: 'Clean teeth, examine patients for oral diseases, and provide preventive care.',
    education: "Associate's degree in dental hygiene",
    outlook: 'Faster than average (7% growth)',
    skills: ['Dental Cleaning', 'Patient Education', 'X-rays', 'Periodontal Care'],
  },

  // Business & Finance
  {
    slug: 'accountant',
    title: 'Accountant',
    category: 'Business',
    medianSalary: 78000,
    percentile25: 58000,
    percentile50: 78000,
    percentile75: 100000,
    percentile90: 130000,
    hourlyMedian: 37.50,
    description: 'Prepare and examine financial records and ensure accuracy.',
    education: "Bachelor's degree in Accounting",
    outlook: 'Average growth (4% growth)',
    skills: ['Financial Reporting', 'Tax Preparation', 'Auditing', 'Excel'],
  },
  {
    slug: 'financial-analyst',
    title: 'Financial Analyst',
    category: 'Business',
    medianSalary: 95000,
    percentile25: 70000,
    percentile50: 95000,
    percentile75: 125000,
    percentile90: 160000,
    hourlyMedian: 45.67,
    description: 'Analyze financial data to help businesses make investment decisions.',
    education: "Bachelor's degree in Finance or related field",
    outlook: 'Faster than average (9% growth)',
    skills: ['Financial Modeling', 'Excel', 'Data Analysis', 'Forecasting'],
  },
  {
    slug: 'marketing-manager',
    title: 'Marketing Manager',
    category: 'Business',
    medianSalary: 145000,
    percentile25: 105000,
    percentile50: 145000,
    percentile75: 190000,
    percentile90: 240000,
    hourlyMedian: 69.71,
    description: 'Plan and execute marketing strategies to promote products or services.',
    education: "Bachelor's degree in Marketing or related field",
    outlook: 'Faster than average (10% growth)',
    skills: ['Marketing Strategy', 'Digital Marketing', 'Analytics', 'Team Leadership'],
  },
  {
    slug: 'human-resources-manager',
    title: 'Human Resources Manager',
    category: 'Business',
    medianSalary: 130000,
    percentile25: 95000,
    percentile50: 130000,
    percentile75: 170000,
    percentile90: 210000,
    hourlyMedian: 62.50,
    description: 'Oversee recruitment, employee relations, and HR policies.',
    education: "Bachelor's degree in HR or related field",
    outlook: 'Faster than average (8% growth)',
    skills: ['Recruitment', 'Employee Relations', 'Compliance', 'Leadership'],
  },
  {
    slug: 'sales-manager',
    title: 'Sales Manager',
    category: 'Business',
    medianSalary: 135000,
    percentile25: 95000,
    percentile50: 135000,
    percentile75: 180000,
    percentile90: 230000,
    hourlyMedian: 64.90,
    description: 'Lead sales teams and develop strategies to meet revenue goals.',
    education: "Bachelor's degree in Business or related field",
    outlook: 'Average growth (5% growth)',
    skills: ['Sales Strategy', 'Team Leadership', 'CRM', 'Negotiation'],
  },
  {
    slug: 'business-analyst',
    title: 'Business Analyst',
    category: 'Business',
    medianSalary: 90000,
    percentile25: 68000,
    percentile50: 90000,
    percentile75: 115000,
    percentile90: 140000,
    hourlyMedian: 43.27,
    description: 'Analyze business processes and recommend improvements.',
    education: "Bachelor's degree in Business or related field",
    outlook: 'Faster than average (11% growth)',
    skills: ['Requirements Gathering', 'Process Improvement', 'SQL', 'Documentation'],
  },
  {
    slug: 'project-manager',
    title: 'Project Manager',
    category: 'Business',
    medianSalary: 105000,
    percentile25: 80000,
    percentile50: 105000,
    percentile75: 135000,
    percentile90: 165000,
    hourlyMedian: 50.48,
    description: 'Plan, execute, and close projects while managing teams and resources.',
    education: "Bachelor's degree plus PMP certification",
    outlook: 'Faster than average (7% growth)',
    skills: ['Project Planning', 'Agile/Scrum', 'Risk Management', 'Leadership'],
  },
  {
    slug: 'management-consultant',
    title: 'Management Consultant',
    category: 'Business',
    medianSalary: 95000,
    percentile25: 70000,
    percentile50: 95000,
    percentile75: 130000,
    percentile90: 170000,
    hourlyMedian: 45.67,
    description: 'Advise organizations on strategy, operations, and performance improvement.',
    education: "Bachelor's or Master's degree in Business",
    outlook: 'Faster than average (11% growth)',
    skills: ['Strategy', 'Problem Solving', 'Presentation', 'Analysis'],
  },

  // Education
  {
    slug: 'teacher',
    title: 'Teacher',
    category: 'Education',
    medianSalary: 65000,
    percentile25: 50000,
    percentile50: 65000,
    percentile75: 80000,
    percentile90: 95000,
    hourlyMedian: 31.25,
    description: 'Educate students in various subjects and grade levels.',
    education: "Bachelor's degree in Education plus teaching license",
    outlook: 'Average growth (4% growth)',
    skills: ['Curriculum Development', 'Classroom Management', 'Communication', 'Patience'],
  },
  {
    slug: 'professor',
    title: 'Professor',
    category: 'Education',
    medianSalary: 85000,
    percentile25: 60000,
    percentile50: 85000,
    percentile75: 115000,
    percentile90: 150000,
    hourlyMedian: 40.87,
    description: 'Teach college-level courses and conduct research.',
    education: 'PhD in field of expertise',
    outlook: 'Faster than average (12% growth)',
    skills: ['Research', 'Teaching', 'Publishing', 'Mentoring'],
  },
  {
    slug: 'school-counselor',
    title: 'School Counselor',
    category: 'Education',
    medianSalary: 62000,
    percentile25: 48000,
    percentile50: 62000,
    percentile75: 78000,
    percentile90: 95000,
    hourlyMedian: 29.81,
    description: 'Help students with academic, career, and personal development.',
    education: "Master's degree in School Counseling",
    outlook: 'Faster than average (10% growth)',
    skills: ['Counseling', 'Student Advocacy', 'Crisis Intervention', 'Communication'],
  },

  // Creative & Design
  {
    slug: 'graphic-designer',
    title: 'Graphic Designer',
    category: 'Creative',
    medianSalary: 58000,
    percentile25: 42000,
    percentile50: 58000,
    percentile75: 78000,
    percentile90: 95000,
    hourlyMedian: 27.88,
    description: 'Create visual concepts to communicate ideas through digital and print media.',
    education: "Bachelor's degree in Graphic Design or related field",
    outlook: 'Average growth (3% growth)',
    skills: ['Adobe Creative Suite', 'Typography', 'Branding', 'Layout Design'],
  },
  {
    slug: 'video-editor',
    title: 'Video Editor',
    category: 'Creative',
    medianSalary: 65000,
    percentile25: 48000,
    percentile50: 65000,
    percentile75: 85000,
    percentile90: 110000,
    hourlyMedian: 31.25,
    description: 'Edit video content for films, television, and digital media.',
    education: "Bachelor's degree in Film or related field",
    outlook: 'Faster than average (7% growth)',
    skills: ['Premiere Pro', 'After Effects', 'Color Grading', 'Storytelling'],
  },
  {
    slug: 'content-writer',
    title: 'Content Writer',
    category: 'Creative',
    medianSalary: 55000,
    percentile25: 40000,
    percentile50: 55000,
    percentile75: 72000,
    percentile90: 90000,
    hourlyMedian: 26.44,
    description: 'Create written content for websites, blogs, and marketing materials.',
    education: "Bachelor's degree in English, Journalism, or related field",
    outlook: 'Faster than average (9% growth)',
    skills: ['Writing', 'SEO', 'Research', 'Editing'],
  },

  // Legal
  {
    slug: 'lawyer',
    title: 'Lawyer',
    category: 'Legal',
    medianSalary: 135000,
    percentile25: 85000,
    percentile50: 135000,
    percentile75: 190000,
    percentile90: 250000,
    hourlyMedian: 64.90,
    description: 'Represent clients in legal matters and provide legal advice.',
    education: 'Juris Doctor (JD) degree and bar admission',
    outlook: 'Faster than average (10% growth)',
    skills: ['Legal Research', 'Litigation', 'Negotiation', 'Writing'],
  },
  {
    slug: 'paralegal',
    title: 'Paralegal',
    category: 'Legal',
    medianSalary: 58000,
    percentile25: 45000,
    percentile50: 58000,
    percentile75: 75000,
    percentile90: 92000,
    hourlyMedian: 27.88,
    description: 'Assist lawyers with legal research, document preparation, and case management.',
    education: "Associate's degree or paralegal certificate",
    outlook: 'Faster than average (12% growth)',
    skills: ['Legal Research', 'Document Preparation', 'Case Management', 'Organization'],
  },

  // Trades & Services
  {
    slug: 'electrician',
    title: 'Electrician',
    category: 'Trades',
    medianSalary: 62000,
    percentile25: 48000,
    percentile50: 62000,
    percentile75: 80000,
    percentile90: 100000,
    hourlyMedian: 29.81,
    description: 'Install, maintain, and repair electrical systems in buildings.',
    education: 'Apprenticeship and licensing',
    outlook: 'Faster than average (8% growth)',
    skills: ['Electrical Systems', 'Troubleshooting', 'Safety', 'Blueprint Reading'],
  },
  {
    slug: 'plumber',
    title: 'Plumber',
    category: 'Trades',
    medianSalary: 60000,
    percentile25: 45000,
    percentile50: 60000,
    percentile75: 78000,
    percentile90: 98000,
    hourlyMedian: 28.85,
    description: 'Install and repair pipes, fixtures, and plumbing systems.',
    education: 'Apprenticeship and licensing',
    outlook: 'Average growth (5% growth)',
    skills: ['Plumbing Systems', 'Problem Solving', 'Customer Service', 'Physical Stamina'],
  },
  {
    slug: 'hvac-technician',
    title: 'HVAC Technician',
    category: 'Trades',
    medianSalary: 55000,
    percentile25: 42000,
    percentile50: 55000,
    percentile75: 70000,
    percentile90: 88000,
    hourlyMedian: 26.44,
    description: 'Install and maintain heating, ventilation, and air conditioning systems.',
    education: 'Technical training and certification',
    outlook: 'Faster than average (6% growth)',
    skills: ['HVAC Systems', 'Troubleshooting', 'Customer Service', 'Refrigeration'],
  },
  {
    slug: 'carpenter',
    title: 'Carpenter',
    category: 'Trades',
    medianSalary: 52000,
    percentile25: 40000,
    percentile50: 52000,
    percentile75: 68000,
    percentile90: 85000,
    hourlyMedian: 25.00,
    description: 'Construct, install, and repair structures and fixtures made of wood.',
    education: 'Apprenticeship or vocational training',
    outlook: 'Average growth (2% growth)',
    skills: ['Carpentry', 'Blueprint Reading', 'Measurement', 'Tool Operation'],
  },
  {
    slug: 'mechanic',
    title: 'Automotive Mechanic',
    category: 'Trades',
    medianSalary: 48000,
    percentile25: 38000,
    percentile50: 48000,
    percentile75: 62000,
    percentile90: 78000,
    hourlyMedian: 23.08,
    description: 'Inspect, maintain, and repair cars and light trucks.',
    education: 'Technical training and ASE certification',
    outlook: 'Average growth (1% growth)',
    skills: ['Automotive Repair', 'Diagnostics', 'Problem Solving', 'Customer Service'],
  },
];

// Helper functions
export function getProfessionBySlug(slug: string): ProfessionData | undefined {
  return professions.find(p => p.slug === slug);
}

export function getProfessionsByCategory(category: string): ProfessionData[] {
  return professions.filter(p => p.category === category);
}

export function getAllCategories(): string[] {
  return Array.from(new Set(professions.map(p => p.category)));
}

export function getAllProfessionSlugs(): string[] {
  return professions.map(p => p.slug);
}
